/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author cpoussie
 */
public class AffichageVies extends javax.swing.JPanel {

        // Identifiant du joueur dans la base de données.
    private final int playerId;

    // Label contenant les cœurs.
    private final JLabel labelVies;

    // Timer permettant d'actualiser régulièrement l'affichage.
    private final Timer timerVies;

    /**
     * Creates new form AffichageVies
     */

    public AffichageVies(int playerId) {
        this.playerId = playerId;

        // Rend le panneau transparent pour l'afficher au-dessus du jeu.
        setOpaque(false);

        // Configuration du texte représentant les vies.
        labelVies = new JLabel();
        labelVies.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 30));
        labelVies.setForeground(Color.RED);

        // Ajout du label dans le panneau.
        add(labelVies);

        // Première lecture du nombre de vies.
        mettreAJourVies();

        // Actualisation des vies toutes les secondes.
        timerVies = new Timer(1000, e -> mettreAJourVies());
        timerVies.start();
    }

    /**
     * Lit le nombre de vies du joueur dans la base de données.
     */
    private void mettreAJourVies() {

        try (
            Connection connexion = DriverManager.getConnection(
                "jdbc:mariadb://nemrod.ens2m.fr:3306/2025-2026_s2_vs1_tp1_honey_run",
                "etudiant",
                "YTDTvj9TR3CDYCmP"
            );

            PreparedStatement requete = connexion.prepareStatement(
                "SELECT lifes FROM `character` WHERE id = ?"
            )
        ) {
            // Recherche le joueur à partir de son identifiant.
            requete.setInt(1, playerId);

            try (ResultSet rs = requete.executeQuery()) {

                if (rs.next()) {
                    int nombreVies = rs.getInt("lifes");

                    // Met à jour l'affichage des cœurs.
                    labelVies.setText(creerCoeurs(nombreVies));
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Crée une chaîne contenant un cœur par vie restante.
     *
     * @param nombreVies nombre de vies restantes
     * @return chaîne contenant les cœurs
     */
    private String creerCoeurs(int nombreVies) {
        StringBuilder coeurs = new StringBuilder();

        for (int i = 0; i < nombreVies; i++) {
            coeurs.append("♥ ");
        }

        return coeurs.toString();
    }

    /**
     * Arrête l'actualisation automatique des vies.
     */
    public void arreter() {
        timerVies.stop();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
