/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author cpoussie
 */

public class Skin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Skin.class.getName());

    /**
     * Creates new form Character
     */
    public boolean isSkinAvailable(String skinName) {
    try {
        Connection connexion = DriverManager.getConnection(
            "jdbc:mariadb://nemrod.caca.fr:3306/caca",
            "nom",
            "MotDePasse"
        );

        PreparedStatement requete = connexion.prepareStatement(
            "SELECT available FROM skins WHERE name = ?"
        );
        requete.setString(1, skinName);

        ResultSet rs = requete.executeQuery();

        if (rs.next()) {
            boolean dispo = rs.getBoolean("available");
            rs.close();
            requete.close();
            connexion.close();
            return dispo;
        }

        rs.close();
        requete.close();
        connexion.close();

    } catch (SQLException e) {
        e.printStackTrace();
    }

    return false; // si erreur → on considère indisponible
}
    private void setButtonImage(javax.swing.JButton button, String resourcePath) {
    java.net.URL imgURL = getClass().getResource(resourcePath);
    if (imgURL == null) {
        System.err.println("Image not found: " + resourcePath);
        System.out.println("Loading: " + resourcePath + " -> " + getClass().getResource(resourcePath));

        return;
    }

    ImageIcon icon = new ImageIcon(imgURL);
    Image scaled = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
    button.setIcon(new ImageIcon(scaled));
    button.setText(""); // enlève le texte
}
    private void loadSkinButtons() {
    setButtonImage(jButton1, "/Interface/Characters/Mante Religieuse Vicieuse.png");

    
    setButtonImage(jButton2, "/Interface/Characters/Criquet Suspect.png");

    
    setButtonImage(jButton3, "/Interface/Characters/Araignee Sans Pitie.png");

    
    setButtonImage(jButton4, "/Interface/Characters/Scarabee Mal Fame.png");
    
    setButtonImage(jButton5, "/Interface/Characters/Abeille Cruelle.png");

    }
    
    private void setupListeners() {
    jButton1.addActionListener(e -> selectSkin("Mante Religieuse Vicieuse"));
    jButton2.addActionListener(e -> selectSkin("Criquet Suspect"));
    jButton3.addActionListener(e -> selectSkin("Araignee Sans Pitie"));
    jButton4.addActionListener(e -> selectSkin("Scarabee Mal Fame"));
    jButton5.addActionListener(e -> selectSkin("Abeille Cruelle"));
}
    private void selectSkin(String skinName) {
    JOptionPane.showMessageDialog(this, "You selected: " + skinName);

    // Ici tu peux stocker le skin dans ton joueur
    // Exemple :
    // Player.currentPlayer.setSkin(skinName);

    dispose(); // ferme la fenêtre
}
    private void checkAvailability() {
    jButton1.setEnabled(isSkinAvailable("Mante Religieuse Vicieuse"));
    jButton2.setEnabled(isSkinAvailable("Criquet Suspect"));
    jButton3.setEnabled(isSkinAvailable("Araignee Sans Pitie"));
    jButton4.setEnabled(isSkinAvailable("Scarabee Mal Fame"));
}

    
    public Skin() {
        initComponents();
        loadSkinButtons();
        checkAvailability();
        setupListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Choose your character");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Skin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
